#!/usr/bin/env bash

set -e

# Verify requirements
command -v brew >/dev/null 2>&1 || { echo "Error: Homebrew no está instalado"; exit 1; }
command -v git >/dev/null 2>&1 || { echo "Error: Git no está instalado"; exit 1; }

CONFIG="install.conf.yaml"
DOTBOT_DIR="dotbot"
DOTBOT_BIN="bin/dotbot"
BASEDIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

cd "${BASEDIR}"

echo "📦 Inicializando submodules..."
git -C "${DOTBOT_DIR}" submodule sync --quiet --recursive
git submodule update --init --recursive "${DOTBOT_DIR}"

echo "🚀 Ejecutando Dotbot..."
"${BASEDIR}/${DOTBOT_DIR}/${DOTBOT_BIN}" -d "${BASEDIR}" --plugin-dir dotbot-brew -c "${CONFIG}" "${@}"